- name: "course2 project wordpress"
  hosts: wordpress
  tasks:
          - name: "install mysql"
            apt:
                    name: mysql-server
                    update_cache: yes
          - name: "Install Dependencies"
            apt:
                    name: "{{ item }}"
            loop:
                    - apache2
                    - ghostscript
                    - libapache2-mod-php
                    - php
                    - php-bcmath
                    - php-curl
                    - php-imagick
                    - php-intl
                    - php-json
                    - php-mbstring
                    - php-mysql
                    - php-xml
                    - php-zip
                    - python3-pymysql
- name: "install wordpress"
  hosts: wordpress
  tasks:
          - name: "installation directory"
            file:
                    path: /srv/www
                    state: directory
                    recurse: yes
                    owner: www-data
                    group: www-data
          - name: "download and extract wordpress"
            unarchive:
                    src: https://wordpress.org/latest.tar.gz
                    dest: /srv/www
                    remote_src: yes
- name: "configure apache for wordpress"
  hosts: wordpress
  tasks:
          - name: "define apache config"
            copy:
                    src: ~/c2project/apache-configuration-file
                    dest: /etc/apache2/sites-available/wordpress.conf
          - name: "enable apache modules"
            shell: "{{ item }}"
            loop:
                    - a2ensite wordpress
                    - a2enmod rewrite
                    - a2dissite 000-default
                    - service apache2 reload
- name: "create MySQL DB and Manage"
  hosts: wordpress
  tasks:
          - name: "Create MySQL DB"
            mysql_db:
                    name: wordpress
                    state: present
                    login_unix_socket: /var/run/mysqld/mysqld.sock
          - name: "MySQL DB user & password"
            mysql_user:
                    name: wordpress
                    password: wordpresspass
                    priv: '*.*:ALL'
                    state: present
                    login_unix_socket: /var/run/mysqld/mysqld.sock
- name: "wordpress config file"
  hosts: wordpress
  tasks:
          - name: "copy config file"
            copy:
                    src: ~/c2project/wp-config.php
                    dest: /srv/www/wordpress/wp-config.php
